services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aiclub_visdial-core_baotg_sd35_v1:latest
    container_name: sd35_visdial_runner
    ipc: host
    shm_size: '16g'
    volumes:
      - .:/workspace
      - ./.cache/huggingface:/workspace/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
